### PR TITLE
Animations, more auth & code refactoring, good stuff

### PR DESCRIPTION
**Pull request by bonham000**
**DID:**
- [Demo](http://g.recordit.co/9drxo0xaW1.gif)
- Cool animations on profile page
- Auth-protected homepage for Dashboard (no longer just `HomePage`)
- Filled out additional routes and renamed components based on discussion with Peter
- Refactored components more, `Dashboard` replaced by `AppContainer`, now at `src/components`, and all 'Dashboard' components separated into `src/components/dashboard/`.
- Added separate styles for Dashboard components

**TO-DO:**
- Finish `Profile` page and wire it to Redux store.
- Get actions ready to update user in database

### CODE REVIEW

**Comment by no-stack-dub-sack** [comment]
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 :tada: :clap: :sparkles: :sparkling_heart:

**Comment by no-stack-dub-sack** [comment]
@bonham000 Looks like you got rid of a small bit of code though that handled presenting the certifications correctly... did you change the server side code at all?

**Comment by no-stack-dub-sack** [comment]
Not sure if I said this yet, but... so pumped.

**Comment by bonham000** [comment]
@no-stack-dub-sack yes the certifications about back after doing that.

Ideally I think the button to trigger dropdown for all the panels should be somewhere else than that `userLabel` but I just put it there for the time being... again this whole page will still be improved so it will probably move.

**Pull request merged**
