### PR TITLE
add CircleCI

### LINKED ISSUE #189: Add CI support
Currently I don't see a Continuous integration pipeline and its imperative to add one as the project evolves.

Some choices are:

[travis](https://travis-ci.org/) - Very popular.
[Circle](https://circleci.com/) - Another good choice.
[codeship](https://codeship.com/) - Another choice.
[werker](http://www.wercker.com/) - This one is from Oracle.

I suggest we choose one and set it up for the project.

### PR DESCRIPTION
**Pull request by smiller171**
Needs @no-stack-dub-sack to set up CircleCI for this to work.
Depends on #222 
fixes #189 

Should configure repo so tests must pass to merge PR

### CODE REVIEW

**Comment by no-stack-dub-sack** [comment]
@smiller171 we should talk about what I need to do to make this work.

**Comment by smiller171** [comment]
@no-stack-dub-sack You need to sign up at circleci.com, add this project, and there's a few settings you should change:
screenshot 2017-07-07 at 9 56 27 pm

**Comment by smiller171** [comment]
@no-stack-dub-sack I'm gonna wait to fix the merge conflicts on this one till after you merge #222.

**Comment by smiller171** [comment]
@no-stack-dub-sack I rebased on master, ready to merge once you have it set up in circleci

**Comment by no-stack-dub-sack** [comment]
@smiller171 wait, I'm making a quick PR to fix some duplicate import statements that weren't caught by GH when you resolved the merge conflicts in the last PR. You'll have to rebase again in one sec.

**Comment by no-stack-dub-sack** [comment]
@smiller171 Ok, never mind, that PR had no effect. still ok.

**Comment by smiller171** [comment]
Yeah, When I rebased this PR it now only affects one brand new file. You won't be able to create conflicts with it.

**Pull request merged**
