### PR TITLE
access user profile from community et al

### PR DESCRIPTION
**Pull request by no-stack-dub-sack**
- super basic implementation of public user profile
   - we should talk about this, because like with opening a private chat from mentorship search, with this method of doing things, you can only open on of these pages at once. We could use `Redirect` component instead of `push(route)` instead, which could give us more flexibility, but we might have to protect the route another way.
- also did a couple of other random things, including addressing the navbar issue in app container. Check that out and let me know. 
- some of the changes are just "staircasing" the code, with no actual changes

### CODE REVIEW

**Comment by bonham000** [comment]
@no-stack-dub-sack yeah this looks great to me. I think this is OK for the profile view. Hopefully we can figure out what's happening if you type in a url like `profile/bonham000` where it doesn't work (but for other routes it does). Otherwise this looks good to me so far.

**Comment by no-stack-dub-sack** [comment]
@bonham000 I think I would have to write some logic on the server to support that... for now, this is all happening on the client, and the user does not get stored in redux until you click on that user's card from the community view. We'd have to do the same thing but with a backend route I believe. And this is also perhaps how we could support more than one user profile being open at once.

**Comment by bonham000** [comment]
I think this is actually more of a problem with React Router. If you type any of the `urls` we've written with a parameter, i.e. `chat/:username`, directly into the browser navigation bar, they are not routed correctly. To me it seems like this treats them like an `a href` and just tries to send the request straight to the server, and we get back the entire page `html`, rather than React Router trying to route them. Perhaps similar to the issue of being unable to navigate to a profile view from within a private chat.

For your point, we should be able to get around that issue by just having the individual profile component fetch it's own user from the `community` when it mounts (or some other way). It can get its user from the router props, similar to what I did in `ChatController`. There should be no need for additional backend support.

**Comment by no-stack-dub-sack** [comment]
@bonham000 Ahh... I see this now. I only saw your other note before.

**Pull request merged**
