### PR TITLE
eradicate homegrown chat code & deps from codebase

### PR DESCRIPTION
**Pull request by no-stack-dub-sack**
@bonham000 sorry man, ~2K lines of code and who knows how many hours of time... 😭 

This doesn't feel quite right - she worked beautifully.

### CODE REVIEW

**Comment by bonham000** [comment]
@no-stack-dub-sack surprised you're working on this so late! I'll merge this.

**Comment by no-stack-dub-sack** [comment]
@bonham000 haha, I wasn't expecting a response so soon. Or a merge, might have been premature actually, was just about to leave a note.

I'm not 100% positive I made the correct changes to the docker config - I got the app up an running, but can't login, getting a proxy error. So something must have gone wrong, because it was working before I pushed this code. 

@smiller171 want to check my work when you see this and try this out and see what might be going on? Everything spins up, but when you try to login it tries to hit the verify-user route, and then just loops you back and spits out the proxy error:
```shell
backend_1    | Express Server is listening on port 8080
mongo_1      | 2017-07-16T07:58:33.415+0000 I NETWORK  [thread1] connection accepted from 172.18.0.4:60352 #7 (1 connection now open)
mongo_1      | 2017-07-16T07:58:33.424+0000 I NETWORK  [conn7] received client metadata from 172.18.0.4:60352 conn7: { driver: { name: "nodejs", version: "2.2.27" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.9.31-moby" }, platform: "Node.js v8.1.4, LE, mongodb-core: 2.1.11" }
backend_1    | Mongoose connected
frontend_1   | Compiled with warnings.
frontend_1   | 
frontend_1   | Warning in ./~/ajv/dist/ajv.bundle.js
frontend_1   | Critical dependencies:
frontend_1   | 1:476-483 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
frontend_1   |  @ ./~/ajv/dist/ajv.bundle.js 1:476-483
frontend_1   | 
frontend_1   | You may use special comments to disable some warnings.
frontend_1   | Use // eslint-disable-next-line to ignore the next line.
frontend_1   | Use /* eslint-disable */ to ignore all warnings in a file.
backend_1    | user already exists
frontend_1   | Proxy error: Could not proxy request /api/user from localhost:3000 to http://localhost:8080.
frontend_1   | See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).
frontend_1   | 
```

**Comment by bonham000** [comment]
@no-stack-dub-sack oops! At first I was going to wait to merge it but I figure you were probably sure about it since deploying w/ Gitter a few days ago and this just removed all the old chat code.

**Comment by no-stack-dub-sack** [comment]
@bonham000 it's all good! Whatever it is will be fixable. The main thing here was removing chat, and that's def still happening, so no worries there. There's just some unforeseen side-effects it seems like.

**Pull request merged**
