### PR TITLE
Added image in Readme.md of the freeCodeCamp alumni network.

### PR DESCRIPTION
**Pull request by jamesjpk123**

### CODE REVIEW

**Comment by no-stack-dub-sack** [comment]
@jamesjpk123 Perfect, thanks! I'll merge this in. Sorry for the late reply, I've been out of pocket for a few days.

**Comment by jamesjpk123** [comment]
Cool! Thanks!

**Comment by jamesjpk123** [comment]
What does squashing commits mean?

**Comment by jamesjpk123** [comment]
I'm really new to this kind of thing.

**Comment by no-stack-dub-sack** [comment]
@jamesjpk123 here's a quick tutorial: https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md#squash-your-commits 

pretty easy and def valuable if you ever want to contribute to FCC (they also require it)

ping me on Gitter if you have any issues!

**Comment by jamesjpk123** [comment]
@no-stack-dub-sack I tried, but I just made more commits! I think I'm going to delete the mess I made, and do all the work in one commit. I will definitely check out a tutorial to Git (probably the one from Code School), as this is a pretty vital skill!

**Comment by jamesjpk123** [comment]
Okay, @no-stack-dub-sack I created a new pull request: #258.

**Comment by no-stack-dub-sack** [comment]
@jamesjpk123 ok great! Thanks! Sorry again for the delay - I've had a very hectic 3 weeks and have essentially been on a quasi vacation. Life is finally back to normal!

**Pull request closed without merging**
